application: daye100032
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: application/static
- url: .*
  script: application.app
libraries:
- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"
