"""empty message

Revision ID: 1441859d4b0c
Revises: 2a21b5c62227
Create Date: 2014-08-25 15:44:56.142000

"""

# revision identifiers, used by Alembic.
revision = '1441859d4b0c'
down_revision = '2a21b5c62227'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('comment', sa.Column('is_secret', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_secret')
    op.drop_column('comment', 'content')
    ### end Alembic commands ###
