"""empty message

Revision ID: 2a21b5c62227
Revises: 8018c490c23
Create Date: 2014-08-18 20:51:28.993000

"""

# revision identifiers, used by Alembic.
revision = '2a21b5c62227'
down_revision = '8018c490c23'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'profile_img')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'profile_image')
    ### end Alembic commands ###
