"""empty message

Revision ID: 8018c490c23
Revises: 54213cfddf45
Create Date: 2014-08-18 19:54:01.246000

"""

# revision identifiers, used by Alembic.
revision = '8018c490c23'
down_revision = '54213cfddf45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_img')
    ### end Alembic commands ###
